/*
 * base.h
 *
 *  Created on: Feb 18, 2025
 *      Author: dhanushscience
 */

#ifndef BASE_H_
#define BASE_H_

#define PERIPHERAL_BASE				(0x40000000UL)

#define APB1_PERIPHERAL_OFFSET		(0x00000000UL)
#define APB1_PERIPHERAL_BASE_ADDR	(PERIPHERAL_BASE + APB1_PERIPHERAL_OFFSET)

#define APB2_PERIPHERAL_OFFSET		(0x00010000UL)
#define APB2_PERIPHERAL_BASE_ADDR	(PERIPHERAL_BASE + APB2_PERIPHERAL_OFFSET)

#define AHB1_PERIPHERAL_OFFSET		(0x00020000UL)
#define AHB1_PERIPHERAL_BASE_ADDR	(PERIPHERAL_BASE + AHB1_PERIPHERAL_OFFSET)

#define AHB2_PERIPHERAL_OFFSET		(0x10000000UL)
#define AHB2_PERIPHERAL_BASE_ADDR	(PERIPHERAL_BASE + AHB2_PERIPHERAL_OFFSET)

#define AHB3_PERIPHERAL_OFFSET		(0x20000000UL)
#define AHB3_PERIPHERAL_BASE_ADDR	(PERIPHERAL_BASE + AHB3_PERIPHERAL_OFFSET)

#define RCC_PERIPHERAL_OFFSET 		(0x00003800)
#define RCC_PERIPHERAL 				(AHB1_PERIPHERAL_BASE_ADDR + RCC_PERIPHERAL_OFFSET)


#endif /* BASE_H_ */
